# Generated by Django 2.0.6 on 2018-06-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='coordinates',
            field=models.CharField(max_length=350, verbose_name='Koordynaty'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='for_sell',
            field=models.BooleanField(default=False, verbose_name='Na sprzedaż'),
        ),
    ]
