# Generated by Django 2.0.6 on 2018-06-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='city',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
