# Generated by Django 2.0.6 on 2018-06-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
