# Generated by Django 2.0.6 on 2018-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0002_auto_20180616_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='Nieaktywność'),
        ),
    ]
