# Generated by Django 2.0.6 on 2018-06-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0002_offer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='surface_unit',
            field=models.CharField(choices=[('HEKTAR', 'Ha'), ('AR', 'Ar'), ('M2', 'm2')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
