# Generated by Django 2.0.6 on 2018-06-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0003_auto_20180616_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='gastronomy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('LOCAL', 'Lokal'), ('PLOT', 'Działka')], max_length=100),
        ),
    ]
