# Generated by Django 2.0.6 on 2018-06-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0004_auto_20180616_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='surface_unit',
        ),
        migrations.AlterField(
            model_name='offer',
            name='surface',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
