# Generated by Django 2.0.6 on 2018-06-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodawarka', '0007_auto_20180616_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='compare_user',
        ),
    ]
