# Generated by Django 2.0.6 on 2018-06-16 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dodawarka', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='profile',
            name='offers_to_compare',
        ),
        migrations.AddField(
            model_name='profile',
            name='offers_to_compare',
            field=models.ManyToManyField(to='dodawarka.Offer'),
        ),
    ]
